### ISSUE TITLE
Support Kotlin DSLs

### ISSUE THREAD

**Issue by musotec** [vierbergenlars/build-aspects-gradle-plugin#35]
I could not get this to work within an hour of debugging; so I'm ultimately moving to another, custom solution.
I believe the current architecture, might not be suited for this use case. As function names like `apply` in `BuildAspectsPlugin` conflict with those in `org.gradle.kotlin.dsl.PluginAware` and other libraries.

**Example (both in build.gradle.kts or in settings.gradle.kts):**
```
    pluginManager.withPlugin("be.vbgn.build-aspects") {
        configure<BuildAspectsPlugin> {
            // below is no good, resolves to PluginAware:
//            apply(project(":project")) {
//
//            }
        }
    }
```
Gradle version I am using is 6.4.1

I just simply do not know enough about Gradle to implement this correctly, and doing so would probably result in a level of effort similar to just adding support myself.

**Reference:** https://docs.gradle.org/current/userguide/kotlin_dsl.html

**Comment by musotec** [comment]
Ended up just using the standard kotlin gradle dsl language and created build variants using inherited source sets (https://kotlinlang.org/docs/reference/mpp-dsl-reference.html#custom-compilations) and expect/actual function definitions to link code between the two. (https://kotlinlang.org/docs/reference/mpp-connect-to-apis.html)

Multi-platform projects are still in alpha. This is apparent in IntelliJ, as it will compile correctly in the IDE, but (at least for custom variants) there will be red error lines present. Expect/Actual is in beta for kotlin as well, so perhaps this is why.

I gotta say though, definitely not easy to follow the documentation as of right now for the kotlin multiplatform dsl. It's also very easy to lose track of scope, as it's not clear what is/isn't available. Also everything is a keyword, so it can be tricky to get into the correct function.

For anyone looking to do this, I would certainly recommend simply writing the code in gradle yourself. Otherwise debugging the issues is almost as difficult as simply writing the solution yourself. (at least for the kotlin dsl)

**Comment by vierbergenlars** [comment]
From your description, it looks like there is a mismatch between what you want to do, and what this plugin does.

Using different sourcesets to create different variants of code is perfectly fine, and I wouldn't recommend using this plugin for that. Since the kotlin plugin seems to automatically create all necessary task when creating an extra sourceset, it is indeed more hassle to set up this plugin than it's worth.

Where this plugin does come in handy, is when you have a system with an extension/plugin architecture where a given version of the extension is compiled against multiple versions of the base system. In that case you have a mostly shared codebase with potentially some version-specific code as well. This is a lot harder to do with sourcesets than with a subproject per version approach. Since pretty much everything is the same, you don't want to maintain N buildscripts.
I tried to describe that case in the readme (https://github.com/vierbergenlars/build-aspects-gradle-plugin#readme, click on "When do I need this plugin?").

I do appreciate the issues you have raised here (`when` being a keyword in Kotlin, issue with a nested `when` being run twice), and I will take a look at them.
